mongodb:
  uri: "mongodb://localhost:27017"
  database: "replant_crop_count"
  collection: "player_counts"
sync:
  period-ticks: 1200
replant:
  delay-ticks: 20
crops:
  - WHEAT
  - CARROT
  - POTATO
  - NETHER_WART
  - BEETROOTS
